title: <p align='center'> Thi Giang </p> 
logo: "/images/logo.png?raw=true" 
description: 
  <p align = 'center'>
  <a href = "pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/thi-giang/">LinkedIn Profile</a> |  
  <a href="https://github.com/Thigiang">Github</a>
  </p>
  <p align='justify'>
  I am pursuing MS degree in Statistics at San Jose State University. 
  <br><br>
  I am actively looking for full-time Data Scientist, Data Analyst, and ML Engineer positions.  
  <br><br>
  </p>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
