title: <p align='center'> Thi Giang </p> 

logo: "/images/logo.png?raw=true" 

description: 
  <p align = 'center'>
  <a href = "pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/thi-giang/">LinkedIn Profile</a> |  
  <a href="https://github.com/Thigiang">Github</a>
  </p>
  <p align='justify'>
  Master of Sciences in Statistics.
  <br><br>
  I have a solid background in traditional statistics and a great interst in Machine Learning and AI. I am actively looking for full-time Data Scientist, Data Analyst, and ML/AI Engineer positions.  
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
