title: <p align='center'> Thi Giang </p> 

logo: "/images/logo.png?raw=true" 

description: 
  <p align = 'center'>
  <a href = "pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/thi-giang/">LinkedIn Profile</a> |  
  <a href="https://github.com/Thigiang">Github</a>
  </p>
  
  <p align='justify'>
  In May 2023, I graduated as one of the best students in spring's cohort of graduates from a master degree in Statistics at San Jose State University. My GPA is 3.87/4.0.  
  <br><br>
  I have a solid background in traditional statistics and an interst in Machine Learning. I am actively looking for full-time Data Scientist, Data Analyst, and ML Engineer positions.  
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
